### ISSUE TITLE
Debug rare exception when refactored file is also renamed

### ISSUE THREAD

**Issue by mauricioaniche** [mauricioaniche/predicting-refactoring-ml#14]
We sometimes have this strange exception where RefactoringMiner finds a refactoring, but we are not able to find the file name in the list of modified files in a commit (probably due to a file Rename).

e.g., In Apache Commons Cli:

```
2020-01-28 17:23:28 INFO  RefactoringAnalyzer:63 Process Commit [8f95e4a724350f9f80429c2af1c3ac9bb2b2c2db] Refactoring: [Rename Class	org.apache.commons.cli.HelpFormatter.StringBufferComparator renamed to org.apache.commons.cli.HelpFormatter.OptionComparator]
2020-01-28 17:23:28 ERROR App:230 Error when collecting commit data
java.lang.RuntimeException: RefactoringMiner finds a refactoring, but we can't find it in DiffEntry: a RENAME_CLASS at org.apache.commons.cli.HelpFormatter.StringBufferComparator
	at refactoringml.RefactoringAnalyzer.collectCommitData(RefactoringAnalyzer.java:93)
	at refactoringml.App.run(App.java:226)
	at integration.ApacheCommonsCliIntegrationTest.before(ApacheCommonsCliIntegrationTest.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:396)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by mauricioaniche** [comment]
Related to #17 and #19

**Comment by mauricioaniche** [comment]
I will close this one for now.
